apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: db
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/service: db
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: postgres:15
          name: {{ .Chart.Name }}-db
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: db-env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Chart.Name }}-pgdata
      volumes:
        - name: {{ .Chart.Name }}-pgdata
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pgdata
