kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: db-env
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ "finebot" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ "finebot" | b64enc | quote }}
