apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/service: db
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      protocol: TCP
      targetPort: postgres
