apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pgdata
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.database.volume.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        {{- toYaml .Values.database.volume.nodeSelectorTerms | nindent 8 }}
