apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-worker
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.workerSchedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: worker
              image: "ghcr.io/abgeo/fine-bot:{{ .Chart.AppVersion }}"
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: {{ .Chart.Name }}-worker-env
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Chart.Name }}-db-env
                      key: POSTGRES_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Chart.Name }}-db-env
                      key: POSTGRES_PASSWORD
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Chart.Name }}-db-env
                      key: POSTGRES_DB
                - name: DATABASE_URL
                  value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(FINE_BOT_DB_SERVICE_HOST):$(FINE_BOT_DB_SERVICE_PORT)/$(DB_NAME)"
